// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsUinGAt2fqffRQkjjTpPxg7H7jpJWaAI',
    appId: '1:763588114877:android:f9065254982417863afad4',
    messagingSenderId: '763588114877',
    projectId: 'sams13-attendanceoperation',
    storageBucket: 'sams13-attendanceoperation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6xJnDKwtGD2YBxX-XIrH5Oby-2abpYc4',
    appId: '1:763588114877:ios:e2003af696229cbd3afad4',
    messagingSenderId: '763588114877',
    projectId: 'sams13-attendanceoperation',
    storageBucket: 'sams13-attendanceoperation.firebasestorage.app',
    iosBundleId: 'com.example.attendanceAndOperations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6xJnDKwtGD2YBxX-XIrH5Oby-2abpYc4',
    appId: '1:763588114877:ios:e2003af696229cbd3afad4',
    messagingSenderId: '763588114877',
    projectId: 'sams13-attendanceoperation',
    storageBucket: 'sams13-attendanceoperation.firebasestorage.app',
    iosBundleId: 'com.example.attendanceAndOperations',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuheboasrj089fkEtKoJSyc8b1mAQy-qE',
    appId: '1:763588114877:web:07190d64c526273b3afad4',
    messagingSenderId: '763588114877',
    projectId: 'sams13-attendanceoperation',
    authDomain: 'sams13-attendanceoperation.firebaseapp.com',
    storageBucket: 'sams13-attendanceoperation.firebasestorage.app',
    measurementId: 'G-HRDMNC70RL',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuheboasrj089fkEtKoJSyc8b1mAQy-qE',
    appId: '1:763588114877:web:506bb871638e3df73afad4',
    messagingSenderId: '763588114877',
    projectId: 'sams13-attendanceoperation',
    authDomain: 'sams13-attendanceoperation.firebaseapp.com',
    storageBucket: 'sams13-attendanceoperation.firebasestorage.app',
    measurementId: 'G-5G8S4CQXWQ',
  );
}